version: "2"

run:
  timeout: 2m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - gocritic
  settings:
    revive:
      rules:
        - name: var-naming
        - name: error-return
        - name: error-strings
        - name: receiver-naming
        - name: indent-error-flow
